name: Task 4 - Creating pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'task_2/**'
  pull_request:
    paths:
      - 'task_2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task_2

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build image
        run: docker-compose build

      - name: Save image as an artifact
        run: docker save task_2_nginx | gzip > task_2_nginx.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-app
          path: task_2_nginx.tar.gz


