name: Task 4 - CI/CD for task_2

on:
  push:
    branches: [ master ]
    paths:
      - 'task_2/**'
  pull_request:
    paths:
      - 'task_2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task_2

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Save Docker image to archive
        run: docker save task_2_nginx | gzip > ./task_2_nginx.tar.gz

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-app
          path: ./task_2_nginx.tar.gz

  deploy:
    runs-on: self-hosted 
    needs: build
    defaults:
      run:
        working-directory: task_2

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: nginx-app

      - name: Load Docker image from archive
        run: gunzip -c task_2_nginx.tar.gz | docker load

      - name: Deploy with Docker Compose
        run: |
          docker-compose down || true
          docker-compose up -d


